Conveyor clash d4 iteration
ethanh20009/ExperimentalSystems20314-15 pull request #13
Opened 2023-04-15 00:32 UTC by jessySodimu

So I have added a little guide that would help the user when they get stuck. This guide tells them what every item is and how it should have been recycled

2023-04-15 08:22 UTC, ethanh20009 requested changes
Needs to be updated from d4Iteration first, and any merge conflicts resolved and made sure its working on your new branch. If it's done this way, we will know its safe to merge into main branch. at the moment, there are a lot of conflicts.

2023-04-15 23:23 UTC, jessySodimu commented
Conflicts should have been fixed or merged
I have added a correction feature which shows the user what mistakes they have made and which ones not

2023-04-16 08:59 UTC, ethanh20009 commented
If you ask for a re review from me I can pull it in.

2023-04-16 16:21 UTC, ethanh20009 approved these changes
Nice!

2023-04-16 16:21 UTC, ethanh20009 commented on RecyclingGame2D/Assets/Scripts/ConveyorBelt/Backups/SpawnRandomPointBackup3.cs
> +        float[] itemsSpawnPositions = { -10.0f, -5.0f, 0.0f, 5.0f, 10.0f };
This may be the reason it doesn't work on phone. General practice is to add gameobjects into the scene and use those as the spawn positions...

E.g. Private Transform spawn1;
.
.
Instantiate(obj, spawn1.position)

2023-04-16 16:21 UTC, merged